In [1]:
'''
once you conda activate your virtual env, 

conda install -c conda-forge gdal

the "-c conda-forge" is a common inclusion when installing packages. 
it means it's maintained at conda-forge instead of the conda mothership.

if you already installed gdal, or pandas etc, numpy should have been included

'''

from osgeo import gdal

import numpy as np  #"as np" means we can refer to the package using "np" in our script--a common abbreviation.



In [2]:
#numpy primer.

#make 5x5 numpy array.

#first make a one-dimensional array
a = np.array(range(25))
print(a.shape)


(25,)


In [5]:
#now reshape it
a.shape = (5,5)
print(a.shape)

(5, 5)


In [6]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [7]:
# a "2-d" numpy array...just like a raster.

#'masking' is a super-powerful numpy feature

mask = a > 13

print(mask)


[[False False False False False]
 [False False False False False]
 [False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [8]:
#cool, huh? with one line of code, you can create a numpy array with the same shape with logical values based on 
# your critera

#note: logical np arrays sum as 0/1
print(np.sum(mask))

11


In [ ]:
#11 simply means there are 11 array values (or cells in your raster) that are > 13 in value.

In [9]:
#let's load a dem raster...yours will be a different path

ds = gdal.Open('/media/john/towt/wetland_atlas/OSM/tiles/417/417__DEM_ALOS.tif', gdal.GA_ReadOnly) #specify read only for play...don't wanna risk changing anything

#note "ds" is a short cut for "datasource"

In [10]:
#now get a band and load the first band of values. bands start at 1
band = ds.GetRasterBand(1)
raster_values = band.ReadAsArray()  #loads data into a numpy array!

print(raster_values.shape)

(606, 954)


In [11]:
print(np.mean(raster_values)) #the mean....sort of...

327.5955


In [13]:
#we didn't account for nodatas yet...
print(band.GetNoDataValue())

-9999.0


In [14]:
#ah, so -9999s were included in the mean

non_nodata_mask = raster_values != -9999
print(np.sum(non_nodata_mask))

578124


In [16]:
#I'd like to 'grab' all of those masked values...easy!

non_nodata_raster_values = raster_values[non_nodata_mask]

print(non_nodata_raster_values.shape) #it grabs them as just a 1-d array

(578124,)


In [17]:
print(np.mean(non_nodata_raster_values))


327.5955


In [18]:
#oh...that's the same mean!  maybe that tells us there are no nodata??
#let's check
print(np.sum(raster_values == -9999))

0


In [ ]:
#ok. I suppose we could have checked first, but then I wouldn't have been able to show you masking in action

In [20]:
#another make-believe operation...
#"what is the mean elevation for the terrain that is above 350m?"

#quickly check if there are any pixels > 350
print(np.sum(raster_values > 350))

95


In [21]:
#make mask:
gt_350_mask = raster_values > 350

print(np.mean(raster_values[gt_350_mask]))


350.78162
